<<<<<<< HEAD
spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev #开发环境
  application:
    name: cloud1-config-aishu-dev
---
spring:
  profiles: test #测试环境
  application:
    name: cloud1-config-aishu-test
# 请保存为UTF-8格式
=======
spring: 
    profiles: 
        active: 
            -dev
---
spring: 
    profiles: dev #开发环境
    application: 
        name: cloud1-config-aishu-dev
---
spring: 
    profiles: test #测试环境
    application: 
        name: cloud1-config-aishu-test
# 请保存为UTF-8格式
>>>>>>> eb688730bc79cdc65de4824f9a227053a6a694d7
